modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="jade"
version="${file.jarVersion}"
displayName="Jade"
authors="Snownee, MorningSage"
displayURL="https://minecraft.curseforge.com/projects/jade"
description="HWYLA addons"

[[dependencies.jade]]
    modId="waila"
    mandatory=true
    versionRange="[1.10.10-B77_1.16.1,)"
    ordering="BEFORE"
    side="BOTH"
